services:
  db:
    container_name: coexist-db
    image: postgres:16
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    # Remove port mapping in production for security
    #ports:
    #  - "5432:5432"

  server:
    container_name: coexist-server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # Remove code volume mounts in production
    #volumes:
    #  - ./server:/app

  client:
    container_name: coexist-client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
    # Remove code volume mounts in production
    #volumes:
    #  - ./client:/app

volumes:
  db-data:
