services:
  db:
    container_name: coexist-db
    image: postgres:16
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
     - "5432:5432"

  server:
    container_name: coexist-server
    image: ghcr.io/codersforcauses/coexist-server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    restart: unless-stopped
    volume:
      - /var/www/coexist.codersforcauses.org/static:/var/www/coexist.codersforcauses.org/static
    env_file: ./server/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    container_name: coexist-client
    image: ghcr.io/codersforcauses/coexist-client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile.prod
    restart: unless-stopped
    env_file: ./client/.env
    environment:
      - APP_ENV=PRODUCTION
    depends_on:
      - server
    ports:
      - "3000:3000"

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: coexist_watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30

volumes:
  db-data: