# Generated by Django 5.0.6 on 2024-07-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rsvp_event_rsvps"),
        ("users", "0002_auto_20240701_0250"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="rsvps",
            field=models.ManyToManyField(related_name="attends", to="event.rsvp"),
        ),
    ]
