# Generated by Django 5.0.6 on 2024-07-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_rsvps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendeduser",
            name="rsvps",
        ),
    ]
