# Generated by Django 5.0.6 on 2024-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_extendeduser_rsvps'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
