# Generated by Django 5.0.6 on 2024-08-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0005_alter_branch_discriminator"),
        ("users", "0006_extendeduser_add_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="branch.branch",
            ),
        ),
    ]
