# Generated by Django 5.0.6 on 2024-07-13 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="discriminator",
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True), # noqa
        ),
    ]
