# Generated by Django 5.0.6 on 2024-07-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"ordering": ["id"]},
        ),
    ]
