# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Branch = apps.get_model("branch", "Branch")
    for row in Branch.objects.all():
        row.discriminator = uuid.uuid4()
        row.save(update_fields=["discriminator"])


class Migration(migrations.Migration):
    dependencies = [
        ("branch", "0002_branch_discriminator"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible. # noqa
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
