# Generated by Django 5.0.6 on 2024-07-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0002_alter_branch_options"),
        ("branch", "0003_populate_branch_discriminator"),
    ]

    operations = []
