# Generated by Django 5.0.6 on 2024-08-03 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0004_merge_20240720_0446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="discriminator",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
