# Generated by Django 5.0.6 on 2024-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rsvp_event_rsvps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="rsvps",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="attended_by", to="event.rsvp"
            ),
        ),
    ]
