# Generated by Django 5.0.6 on 2024-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="event",
            name="payment_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
