# Generated by Django 5.0.6 on 2024-07-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_image"),
        ("event", "0003_alter_event_rsvps"),
    ]

    operations = []
