# Generated by Django 5.0.6 on 2024-07-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_event_payment_link"),
        ("event", "0006_merge_20240709_0905"),
    ]

    operations = []
