# Generated by Django 5.0.6 on 2024-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_merge_20240710_0852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="payment_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
