# Generated by Django 5.0.6 on 2024-07-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_location_url'),
        ('event', '0008_rename_branch_event_branch_id'),
    ]

    operations = [
    ]
