# Generated by Django 5.0.6 on 2024-07-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_location_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
