# Generated by Django 5.1.2 on 2024-11-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_location_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_url',
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
